replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/lyrical-mason-465314-f4/go-services/payment-service
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 8081

env:
  GCP_PROJECT_ID: lyrical-mason-465314-f4
  DB_PORT: 5432
  DB_NAME: orderpaymentdb
  DB_USER: postgres
  DB_HOST: 34.57.113.181
  ORDER_SUBSCRIPTION_ID: orderpayment-sub
