apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8082
          env:
            - name: GCP_PROJECT_ID
              value: {{ .Values.env.GCP_PROJECT_ID | quote }}
            - name: DB_PORT
              value: {{ .Values.env.DB_PORT | quote }}
            - name: DB_NAME
              value: {{ .Values.env.DB_NAME | quote }}
            - name: DB_USER
              value: {{ .Values.env.DB_USER | quote }}
            - name: DB_HOST
              value: {{ .Values.env.DB_HOST | quote }}
            - name: payment_TOPIC_ID
              value: {{ .Values.env.payment_TOPIC_ID | quote }}
            - name: payment_SUBSCRIPTION_ID
              value: {{ .Values.env.payment_SUBSCRIPTION_ID | quote }}  