apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  type: LoadBalancer
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
